<?php
// Copyright 1999-2016. Parallels IP Holdings GmbH.
?>
<?php echo $this->form; ?>
<?php echo $this->renderSmallTools($this->tasksbuttons); ?>
<script>
    Jsw.onReady(function () {
        $$('.actions-box .s-btn').invoke('observe', 'click', function (event) {
            this.setAttribute('href', this.getAttribute('href') + '/domainId/' + $('exampleSelect').value);
        });
    });
</script>
